// src/lib/home/ForTeamsSection.svelte
<script lang="ts">
  import { homeTranslations, type Locale } from '@shumoku/website-content'
  import CoreNode from './CoreNode.svelte'
  import DashedConnector from './DashedConnector.svelte'

  import SatelliteNode from './SatelliteNode.svelte'
  import { buttonStyles, cn, sectionStyles } from './styles'

  const nodeIcons = [
    { name: 'Code2', class: 'w-5 h-5' },
    { name: 'Package', class: 'w-5 h-5' },
    { name: 'Plug', class: 'w-5 h-5' },
    { name: 'MapIcon', class: 'w-5 h-5' },
  ]
  let { locale }: { locale: string } = $props()
  const t = $derived(homeTranslations[locale as Locale]?.forTeams ?? homeTranslations.en.forTeams)
</script>
<section class={cn('relative overflow-hidden', sectionStyles.padding)}>
  <div class="max-w-4xl mx-auto">
    <p class="text-sm text-emerald-600 dark:text-emerald-400/80 text-center leading-relaxed mb-6">
      {t.tagline1}
      <br>
      {t.tagline2}
    </p>

    <h2 class={cn(sectionStyles.title, 'text-center mb-16')}>{t.title}</h2>

    <div class="hidden lg:flex flex-col items-center">
      <SatelliteNode
        title={t.nodes[0].title}
        description={t.nodes[0].description}
        icon={nodeIcons[0]}
      ></SatelliteNode>
      <DashedConnector orientation="vertical"></DashedConnector>

      <div class="flex items-center justify-center">
        <SatelliteNode
          title={t.nodes[1].title}
          description={t.nodes[1].description}
          icon={nodeIcons[1]}
        ></SatelliteNode>
        <DashedConnector orientation="horizontal"></DashedConnector>
        <CoreNode></CoreNode>
        <DashedConnector orientation="horizontal"></DashedConnector>
        <SatelliteNode
          title={t.nodes[2].title}
          description={t.nodes[2].description}
          icon={nodeIcons[2]}
        ></SatelliteNode>
      </div>
      <DashedConnector orientation="vertical"></DashedConnector>

      <SatelliteNode
        title={t.nodes[3].title}
        description={t.nodes[3].description}
        icon={nodeIcons[3]}
      ></SatelliteNode>
    </div>

    <div class="lg:hidden flex flex-col items-center gap-8">
      <CoreNode></CoreNode>
      <div class="grid grid-cols-2 gap-6 max-w-sm">
        {#each t.nodes as node, i}
          <SatelliteNode
            title={node.title}
            description={node.description}
            icon={nodeIcons[i]}
          ></SatelliteNode>
        {/each}
      </div>
    </div>

    <div class="flex flex-wrap items-center justify-center gap-2 mt-14">
      <span class="text-xs font-semibold text-neutral-500 uppercase tracking-wider mr-1">
        {t.roadmapLabel}
      </span>
      {#each t.roadmap as item}
        <div
          class="flex items-center gap-1.5 px-2.5 py-1 rounded-full border border-neutral-200/70 dark:border-neutral-700/50 bg-white dark:bg-neutral-800"
        >
          <div class="w-1.5 h-1.5 rounded-full bg-emerald-500"></div>
          <span class="text-xs text-neutral-600 dark:text-neutral-400">{item}</span>
        </div>
      {/each}
    </div>

    <p
      class="text-xs text-neutral-500 dark:text-neutral-500 text-center max-w-xl mx-auto mt-10 leading-relaxed"
    >
      {t.supportNote}{' '}
      <a
        href={`/${locale}#enterprise`}
        class="font-medium text-emerald-600 dark:text-emerald-400 hover:underline whitespace-nowrap"
      >
        {t.supportCta}
        →
      </a>
    </p>

    <div class="text-center mt-6">
      <a href="mailto:contact@shumoku.dev" class={cn(...buttonStyles.primary)}> {t.cta} </a>
    </div>
  </div>
</section>

// components/home/ForTeamsSection.tsx
import { Code2, MapIcon, Package, Plug } from 'lucide-react'
import Link from 'next/link'
import { cn } from '@/lib/cn'
import { buttonStyles, sectionStyles } from './styles'
import { homeTranslations, type Locale } from './translations'

const nodeIcons = [
  <Code2 key="plugin" className="w-5 h-5" />,
  <Package key="embed" className="w-5 h-5" />,
  <Plug key="api" className="w-5 h-5" />,
  <MapIcon key="roadmap" className="w-5 h-5" />,
]

function CoreNode() {
  return (
    <div className="relative flex items-center justify-center">
      <div className="absolute w-28 h-28 rounded-full bg-emerald-500/10 blur-xl" />
      <div className="relative w-20 h-20 rounded-full bg-white dark:bg-neutral-900 border border-emerald-500/30 flex items-center justify-center shadow-lg shadow-emerald-500/10">
        <img src="/logo-symbol.svg" alt="Shumoku" className="w-10 h-10" />
      </div>
    </div>
  )
}

function SatelliteNode({
  title,
  description,
  icon,
}: {
  title: string
  description: string
  icon: React.ReactNode
}) {
  return (
    <div className="flex flex-col items-center gap-2 w-40">
      <div className="w-11 h-11 rounded-xl bg-emerald-50 dark:bg-emerald-900/30 border border-emerald-200/50 dark:border-emerald-700/30 flex items-center justify-center text-emerald-600 dark:text-emerald-400">
        {icon}
      </div>
      <div className="text-center">
        <div className="text-sm font-semibold">{title}</div>
        <div className="text-xs text-neutral-500 dark:text-neutral-500 mt-0.5">{description}</div>
      </div>
    </div>
  )
}

function DashedConnector({ orientation }: { orientation: 'vertical' | 'horizontal' }) {
  if (orientation === 'vertical') {
    return (
      <div className="flex justify-center py-1">
        <div className="w-px h-10 border-l-2 border-dashed border-emerald-300 dark:border-emerald-700/40" />
      </div>
    )
  }
  return (
    <div className="flex items-center px-2">
      <div className="h-px w-12 border-t-2 border-dashed border-emerald-300 dark:border-emerald-700/40" />
    </div>
  )
}

export function ForTeamsSection({ locale }: { locale: string }) {
  const t = homeTranslations[locale as Locale]?.forTeams ?? homeTranslations.en.forTeams

  return (
    <section className={cn('relative overflow-hidden', sectionStyles.padding)}>
      <div className="max-w-4xl mx-auto">
        {/* Tagline */}
        <p className="text-sm text-emerald-600 dark:text-emerald-400/80 text-center leading-relaxed mb-6">
          {t.tagline1}
          <br />
          {t.tagline2}
        </p>

        {/* Title */}
        <h2 className={cn(sectionStyles.title, 'text-center mb-16')}>{t.title}</h2>

        {/* Desktop: center-core cross layout */}
        <div className="hidden lg:flex flex-col items-center">
          {/* Top node */}
          <SatelliteNode
            title={t.nodes[0].title}
            description={t.nodes[0].description}
            icon={nodeIcons[0]}
          />
          <DashedConnector orientation="vertical" />

          {/* Middle row: left — center — right */}
          <div className="flex items-center justify-center">
            <SatelliteNode
              title={t.nodes[1].title}
              description={t.nodes[1].description}
              icon={nodeIcons[1]}
            />
            <DashedConnector orientation="horizontal" />
            <CoreNode />
            <DashedConnector orientation="horizontal" />
            <SatelliteNode
              title={t.nodes[2].title}
              description={t.nodes[2].description}
              icon={nodeIcons[2]}
            />
          </div>

          <DashedConnector orientation="vertical" />
          {/* Bottom node */}
          <SatelliteNode
            title={t.nodes[3].title}
            description={t.nodes[3].description}
            icon={nodeIcons[3]}
          />
        </div>

        {/* Mobile: stacked layout */}
        <div className="lg:hidden flex flex-col items-center gap-8">
          <CoreNode />
          <div className="grid grid-cols-2 gap-6 max-w-sm">
            {t.nodes.map((node, i) => (
              <SatelliteNode
                key={node.title}
                title={node.title}
                description={node.description}
                icon={nodeIcons[i]}
              />
            ))}
          </div>
        </div>

        {/* Roadmap pills */}
        <div className="flex flex-wrap items-center justify-center gap-2 mt-14">
          <span className="text-xs font-semibold text-neutral-500 uppercase tracking-wider mr-1">
            {t.roadmapLabel}
          </span>
          {t.roadmap.map((item) => (
            <div
              key={item}
              className="flex items-center gap-1.5 px-2.5 py-1 rounded-full border border-neutral-200/70 dark:border-neutral-700/50 bg-white dark:bg-neutral-800"
            >
              <div className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
              <span className="text-xs text-neutral-600 dark:text-neutral-400">{item}</span>
            </div>
          ))}
        </div>

        {/* Community vs commercial boundary */}
        <p className="text-xs text-neutral-500 dark:text-neutral-500 text-center max-w-xl mx-auto mt-10 leading-relaxed">
          {t.supportNote}{' '}
          <Link
            href={`/${locale}#enterprise`}
            className="font-medium text-emerald-600 dark:text-emerald-400 hover:underline whitespace-nowrap"
          >
            {t.supportCta} →
          </Link>
        </p>

        {/* CTA */}
        <div className="text-center mt-6">
          <a href="mailto:contact@shumoku.dev" className={cn(...buttonStyles.primary)}>
            {t.cta}
          </a>
        </div>
      </div>
    </section>
  )
}
